### ISSUE TITLE
[DB] 6월 1일에 UPDATE 될 사항들

### ISSUE THREAD

**Issue by ddusi** [Hobak-Goguma/DaangnMarket#75]
- 매너온도 log 테이블 개편
![KakaoTalk_20200526_153127919](https://user-images.githubusercontent.com/58924238/82867794-68aefb00-9f66-11ea-860a-b9a90223acb6.png)

**Comment by DevLeeSeonwoo** [comment]
product 'addr' column add

**Comment by ddusi** [comment]
company column change data type 
 - json > varchar(200)

**Comment by ddusi** [comment]
member Table, udate, lastdate column null permit
